The-Enthusiast-404/git-begin

@/components/ui/select.tsx
app/components/FilterForm.tsx
app/routes/_index.tsx
app/services/github.ts
app/services/gitlab.ts
app/types/index.ts
package-lock.json
package.json

fixes: #3 
Added multiple categories to filter issues

added issue filtering by category

---

app/components/FilterForm.tsx
app/routes/_index.tsx
app/services/github.ts
app/services/gitlab.ts
app/types/index.ts

added ability to seach issues for specific frameworks

---

.gitignore
env.d.ts
netlify.toml
package-lock.json
package.json
vite.config.ts

Deployed web app in netlify. In future will move this to cloudflare

deploy: added deployment config

---

@/components/ui/tooltip.tsx
app/components/FilterForm.tsx
app/components/IssueCard.tsx
package-lock.json
package.json

closes #11 
- issues are opening in new tab
- disabled gitlab button with a tooltip

feat: Feature new tab issues

---

app/components/FilterForm.tsx
app/components/IssueCard.tsx
app/routes/_index.tsx
app/services/github.ts
app/types/index.ts

closes #12 
- Added PR filter
- Showing Pr icon to let users knkow if it has PRs or not

feat: Feature pr

---

@/components/ui/scroll-area.tsx
app/routes/_index.tsx
package-lock.json
package.json

closes #17 
- fixed the sidebar
- kept the responsive UI the same

feat: updated sidebar to be fixed

---

app/components/ToggleTheme.tsx

feat: updated toggle theme button

---

app/components/IssueCard.tsx
app/icons/index.tsx

feat: Feature language icons

---

app/components/Footer.tsx
app/components/IssueCard.tsx
app/components/NavBar.tsx
app/routes/_index.tsx

Feature footer

---

app/routes/_index.tsx
app/services/github.ts

fix: improved realiability of issue fetching

---

app/routes/_index.tsx
package-lock.json
package.json
tailwind.config.js

fix: Feature UI

---

app/components/BookmarkButton.tsx
app/components/FilterForm.tsx
app/components/IssueCard.tsx
app/hooks/useBookmarks.ts
app/routes/_index.tsx

feat: Feat bookmark

---

app/routes/_index.tsx
app/services/github.ts

fix: fixed assigned filter

---

app/data/categories.ts

closes #34 
Added some more categories for more smooth user experience

categories.ts updated

---

app/services/github.ts

Resolves #49
Modified Graphql query and logic to only return:
Issues with HasPRs: False
Issues with HasPRs: True if State is Open, Draft, closed, or NULL.
Some cases showed HasPR: True but state: Null. Manually reviewed and did not see any PRs for the mentioned issue, this could be a github API bug.

Fix graphql

---

app/components/NavBar.tsx
package-lock.json
package.json

closes #61 
changed github Icon  to look like the one in the Hugo website

changed GitHub  icon

---

app/components/Footer.tsx

feat: added the text

---

app/components/FilterForm.tsx

This pull request address issue #59,  improving the appearance of the multi-select language filter.
- Fixed alignment and padding issues in the search box and input field.
- Conditionally display "Select Languages" placeholder when no languages are selected.
- Resolves #59 
https://github.com/user-attachments/assets/d41b8a95-874f-49fa-84ff-d81d11239829

Improve Multi Select Language Filter Appreance (Fixes #59)

---

app/root.tsx

This pull request has changes based on issue #63, that is about adding meta description to the website
- Added meta description with text sent by @dotslashbit 
Resolves #63

Add meta description (#63)

---

.husky/pre-commit
app/components/Footer.tsx
package.json

This pull request has changes based on issue #70 , that is about changing layout of Footer
- Changed Footer to be column even on desktop so the text is on top of the icons. Icons are below of text but with the right padding
- It's all centered and responsive for desktop, tablet and mobile
- Updated package-lock to remove vulnerabilities. The website works like normal
- Remove .husky first two lines in pre-commit file because of warning when testing the website. The website works like normal
Resolves #70

Fix: Change Footer layout

---

.husky/pre-commit
__tests__/services/github.test.ts
app/services/github.ts
jest.config.js
package-lock.json
package.json

- Added Jest Test for testing
- Added `jest-mock-extended` for mocking and other pre-made functions that help in testing
- Added testing in the pre-commit rule that opposes everyone adding failing tests to push
Run the command
```bash
npm run test
```

Added Jest Testing Config

---

__tests__/services/github.test.ts
app/data/defaults.ts
app/routes/_index.tsx

Added a constant with all default values, and only submitted the form data with the changed params only
Fixes #54

Add defaults for each filter and change query when necessary
